name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3

      - name: Move Changed Files to tmp folder
        run: |
          mkdir ./tmptrivy
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            FILESIZE = $(stat -c%s "$file")
            if [ $FILESIZE -lt 25000000 ]
              echo $FILESIZE
              cp $file ./tmptrivy
          ls ./tmptrivy
          done

      # Run Trivy Scan in non-failure mode
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './tmptrivy'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Upload Findings to GitHub
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'